version: "2"
services:
  app:
    container_name: cms-menu
    build:
      context: .
      dockerfile: .docker/Dockerfile-dev
    volumes:
      - ./:/go/src/github.com/anhhuy1010/cms-menu
    ports:
      - 8001:8001
      - 5001:5001

